root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - "import"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - prettier/@typescript-eslint
    - plugin:prettier/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
rules:
    import/order:
        - error
        - alphabetize:
            order: asc
