blank_issues_enabled: false
contact_links:
  - name: Homebridge Slack
    url: https://homebridge-slackin.glitch.me/
    about: "Join the #homebridge-scout channel for plugin-specific support and updates."
