name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Install Dependencies
      run: sudo apt-get install jq
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
      env:
        CI: true
    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json
        flags: unittests
        fail_ci_if_error: true
    - name: Pack
      run: npm pack
    - name: Get Package Name/Version
      run: |
        NPM_PACKAGE=`cat package.json | jq -r '"\(.name)-\(.version)"'`
        echo "NPM_PACKAGE=$NPM_PACKAGE" >> $GITHUB_ENV
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NPM_PACKAGE }}
        path: ${{ env.NPM_PACKAGE }}.tgz
